// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageBid    int64                  `protobuf:"varint,1,opt,name=message_bid,json=messageBid,proto3" json:"message_bid,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Bid) GetMessageBid() int64 {
	if x != nil {
		return x.MessageBid
	}
	return 0
}

func (x *Bid) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Bid) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageResult int64                  `protobuf:"varint,1,opt,name=message_result,json=messageResult,proto3" json:"message_result,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetMessageResult() int64 {
	if x != nil {
		return x.MessageResult
	}
	return 0
}

func (x *Result) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Result) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type Heartbeat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Succes           bool                   `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	LogicalTime      int64                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	HighestBid       int64                  `protobuf:"varint,3,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	ElapsedTime      int64                  `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	Done             bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	HighestBidderNow string                 `protobuf:"bytes,6,opt,name=highest_bidder_now,json=highestBidderNow,proto3" json:"highest_bidder_now,omitempty"`
	ArrayBids        []string               `protobuf:"bytes,7,rep,name=array_bids,json=arrayBids,proto3" json:"array_bids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

func (x *Heartbeat) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Heartbeat) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *Heartbeat) GetElapsedTime() int64 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

func (x *Heartbeat) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Heartbeat) GetHighestBidderNow() string {
	if x != nil {
		return x.HighestBidderNow
	}
	return ""
}

func (x *Heartbeat) GetArrayBids() []string {
	if x != nil {
		return x.ArrayBids
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Ack) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type CurrentBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Money         int64                  `protobuf:"varint,1,opt,name=money,proto3" json:"money,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBid) Reset() {
	*x = CurrentBid{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBid) ProtoMessage() {}

func (x *CurrentBid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBid.ProtoReflect.Descriptor instead.
func (*CurrentBid) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *CurrentBid) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *CurrentBid) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *CurrentBid) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"f\n" +
	"\x03bid\x12\x1f\n" +
	"\vmessage_bid\x18\x01 \x01(\x03R\n" +
	"messageBid\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x03R\vlogicalTime\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"o\n" +
	"\x06result\x12%\n" +
	"\x0emessage_result\x18\x01 \x01(\x03R\rmessageResult\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x03R\vlogicalTime\"\xeb\x01\n" +
	"\theartbeat\x12\x16\n" +
	"\x06succes\x18\x01 \x01(\bR\x06succes\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x03R\vlogicalTime\x12\x1f\n" +
	"\vhighest_bid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12!\n" +
	"\felapsed_time\x18\x04 \x01(\x03R\velapsedTime\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x12,\n" +
	"\x12highest_bidder_now\x18\x06 \x01(\tR\x10highestBidderNow\x12\x1d\n" +
	"\n" +
	"array_bids\x18\a \x03(\tR\tarrayBids\"X\n" +
	"\x03ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x03R\vlogicalTime\"_\n" +
	"\n" +
	"currentBid\x12\x14\n" +
	"\x05money\x18\x01 \x01(\x03R\x05money\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x03R\vlogicalTime\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\a\n" +
	"\x05empty2a\n" +
	"\vReplication\x12\x11\n" +
	"\x03Bid\x12\x04.bid\x1a\x04.ack\x12\x1e\n" +
	"\x06Result\x12\a.result\x1a\v.currentBid\x12\x1f\n" +
	"\tHeartbeat\x12\n" +
	".heartbeat\x1a\x06.emptyB\x18Z\x16Replication/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proto_goTypes = []any{
	(*Bid)(nil),        // 0: bid
	(*Result)(nil),     // 1: result
	(*Heartbeat)(nil),  // 2: heartbeat
	(*Ack)(nil),        // 3: ack
	(*CurrentBid)(nil), // 4: currentBid
	(*Empty)(nil),      // 5: empty
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: Replication.Bid:input_type -> bid
	1, // 1: Replication.Result:input_type -> result
	2, // 2: Replication.Heartbeat:input_type -> heartbeat
	3, // 3: Replication.Bid:output_type -> ack
	4, // 4: Replication.Result:output_type -> currentBid
	5, // 5: Replication.Heartbeat:output_type -> empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
