// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chit_Chat_Join_FullMethodName    = "/Chit_Chat/Join"
	Chit_Chat_Publish_FullMethodName = "/Chit_Chat/Publish"
	Chit_Chat_Leave_FullMethodName   = "/Chit_Chat/Leave"
)

// Chit_ChatClient is the client API for Chit_Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Chit_ChatClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Ack, error)
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*Ack, error)
}

type chit_ChatClient struct {
	cc grpc.ClientConnInterface
}

func NewChit_ChatClient(cc grpc.ClientConnInterface) Chit_ChatClient {
	return &chit_ChatClient{cc}
}

func (c *chit_ChatClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chit_Chat_ServiceDesc.Streams[0], Chit_Chat_Join_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinRequest, ChatMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chit_Chat_JoinClient = grpc.ServerStreamingClient[ChatMessage]

func (c *chit_ChatClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Chit_Chat_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chit_ChatClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Chit_Chat_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Chit_ChatServer is the server API for Chit_Chat service.
// All implementations must embed UnimplementedChit_ChatServer
// for forward compatibility.
type Chit_ChatServer interface {
	Join(*JoinRequest, grpc.ServerStreamingServer[ChatMessage]) error
	Publish(context.Context, *PublishRequest) (*Ack, error)
	Leave(context.Context, *LeaveRequest) (*Ack, error)
	mustEmbedUnimplementedChit_ChatServer()
}

// UnimplementedChit_ChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChit_ChatServer struct{}

func (UnimplementedChit_ChatServer) Join(*JoinRequest, grpc.ServerStreamingServer[ChatMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedChit_ChatServer) Publish(context.Context, *PublishRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedChit_ChatServer) Leave(context.Context, *LeaveRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedChit_ChatServer) mustEmbedUnimplementedChit_ChatServer() {}
func (UnimplementedChit_ChatServer) testEmbeddedByValue()                   {}

// UnsafeChit_ChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Chit_ChatServer will
// result in compilation errors.
type UnsafeChit_ChatServer interface {
	mustEmbedUnimplementedChit_ChatServer()
}

func RegisterChit_ChatServer(s grpc.ServiceRegistrar, srv Chit_ChatServer) {
	// If the following call pancis, it indicates UnimplementedChit_ChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chit_Chat_ServiceDesc, srv)
}

func _Chit_Chat_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Chit_ChatServer).Join(m, &grpc.GenericServerStream[JoinRequest, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chit_Chat_JoinServer = grpc.ServerStreamingServer[ChatMessage]

func _Chit_Chat_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Chit_ChatServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chit_Chat_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Chit_ChatServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chit_Chat_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Chit_ChatServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chit_Chat_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Chit_ChatServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chit_Chat_ServiceDesc is the grpc.ServiceDesc for Chit_Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chit_Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chit_Chat",
	HandlerType: (*Chit_ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Chit_Chat_Publish_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _Chit_Chat_Leave_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Join",
			Handler:       _Chit_Chat_Join_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto.proto",
}
