// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Chit_ChatClient is the client API for Chit_Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Chit_ChatClient interface {
	Bid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Ack, error)
	Result(ctx context.Context, in *Result, opts ...grpc.CallOption) (*CurrentBid, error)
	Heartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*Empty, error)
}

type chit_ChatClient struct {
	cc grpc.ClientConnInterface
}

func NewChit_ChatClient(cc grpc.ClientConnInterface) Chit_ChatClient {
	return &chit_ChatClient{cc}
}

func (c *chit_ChatClient) Bid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/Chit_Chat/Bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chit_ChatClient) Result(ctx context.Context, in *Result, opts ...grpc.CallOption) (*CurrentBid, error) {
	out := new(CurrentBid)
	err := c.cc.Invoke(ctx, "/Chit_Chat/Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chit_ChatClient) Heartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Chit_Chat/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Chit_ChatServer is the server API for Chit_Chat service.
// All implementations must embed UnimplementedChit_ChatServer
// for forward compatibility
type Chit_ChatServer interface {
	Bid(context.Context, *Bid) (*Ack, error)
	Result(context.Context, *Result) (*CurrentBid, error)
	Heartbeat(context.Context, *Heartbeat) (*Empty, error)
	mustEmbedUnimplementedChit_ChatServer()
}

// UnimplementedChit_ChatServer must be embedded to have forward compatible implementations.
type UnimplementedChit_ChatServer struct {
}

func (UnimplementedChit_ChatServer) Bid(context.Context, *Bid) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedChit_ChatServer) Result(context.Context, *Result) (*CurrentBid, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedChit_ChatServer) Heartbeat(context.Context, *Heartbeat) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedChit_ChatServer) mustEmbedUnimplementedChit_ChatServer() {}

// UnsafeChit_ChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Chit_ChatServer will
// result in compilation errors.
type UnsafeChit_ChatServer interface {
	mustEmbedUnimplementedChit_ChatServer()
}

func RegisterChit_ChatServer(s grpc.ServiceRegistrar, srv Chit_ChatServer) {
	s.RegisterService(&Chit_Chat_ServiceDesc, srv)
}

func _Chit_Chat_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Chit_ChatServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chit_Chat/Bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Chit_ChatServer).Bid(ctx, req.(*Bid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chit_Chat_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Result)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Chit_ChatServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chit_Chat/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Chit_ChatServer).Result(ctx, req.(*Result))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chit_Chat_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Heartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Chit_ChatServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chit_Chat/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Chit_ChatServer).Heartbeat(ctx, req.(*Heartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

// Chit_Chat_ServiceDesc is the grpc.ServiceDesc for Chit_Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chit_Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chit_Chat",
	HandlerType: (*Chit_ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _Chit_Chat_Bid_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _Chit_Chat_Result_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Chit_Chat_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
